### ISSUE TITLE
Request for improvements

### ISSUE THREAD

**Issue by Tavarelemos** [habibieamrullah/WhatsUpShop#2]
1° Allow the alteration or deletion of items created as (VARIANTS/VARIATIONS) of the product. because once registered, you cannot change it, you can only change it if it is directly through the database or by deleting the product and registering everything again. and that's not productive.

2° When registering (ADDITIONAL IMAGES) for the product and if for some reason the user needs to change these additional images, eg: Exchange one photo for another. he cannot perform the operation, being necessary to delete the product and register everything again.

these two items above are from the product registration on the panel (admin.php)

And finally, ideally when completing the shopping cart order process. the cart was automatically cleaned after confirming the order.

these improvements are essential to making the project worthwhile.

the rest is amazing and I do intend to contribute payments soon for you. for it is really deserved. big hug.

**Comment by habibieamrullah** [comment]
Hello there...

Your plan to contribute donation payments is amazing 😄 

Oh ya, both features are already exist in this project... Watch this video:
[](https://www.youtube.com/watch?v=NRy8SnLLpe4) 
- minutes 12:40 -> you can add additional product images to any product.. but first you must upload your additional images to "Pictures" section. I demonstrated it actually on minutes 12:55
- minutes 13:35 -> You can add options to your product, such as medium, small, large, etc... it's completely adjustable.
- minutes 16:47 -> On home section of admin panel, you can definitely edit your product by clicking edit link on each product list.

Please let me know why did not you see these features while they are already exist.

Thanks anyway.

**Comment by Tavarelemos** [comment]
I want to apologize for question number 2 because I have a .htaccess on my server that was implying the operation of this operation. therefore disregard this question number 2

**Comment by Tavarelemos** [comment]
> Olá...
> 
> Seu plano de contribuir com pagamentos de doações é incrível 😄
> 
> Ah sim, os dois recursos já existem neste projeto ... Assista a este vídeo:
> 
> * minutos 12:40 -> você pode adicionar imagens de produtos adicionais a qualquer produto .. mas primeiro você deve fazer upload de suas imagens adicionais para a seção "Imagens". Na verdade, eu demonstrei isso aos minutos 12:55
> * minutos 13:35 -> Você pode adicionar opções ao seu produto, como médio, pequeno, grande, etc ... é totalmente ajustável.
> * minutos 16:47 -> Na seção inicial do painel de administração, você pode definitivamente editar seu produto clicando no link editar em cada lista de produtos.
> 
> Informe por que você não viu esses recursos enquanto eles já existem.
> 
> Obrigado mesmo assim.

Minutes 13:35 -> User can add variations without problems. but after the record has been saved, the user cannot change that field. so the user has to delete the entire record and register everything again. you can run the test yourself and you will see that you cannot change it.

**Comment by Tavarelemos** [comment]
Sorry, I'm from Brazil and I use Google translator to write to you. and because of that maybe what he said was not clear. but, I've already watched your entire uncut video on your YouTube channel. which is even very good. but, in fact, ignore the question of number (2°) as it was my .HTACCESS file that was causing the system to function. but the other issues I mentioned are in fact essential.

**Comment by habibieamrullah** [comment]
Okay no problem... so please make some donation payment to my PayPal then I will improve this problem you mentioned: "but after the record has been saved, the user cannot change that field. so the user has to delete the entire record and register everything again"

**Comment by Tavarelemos** [comment]
> Ok, não tem problema ... então, por favor, faça algum pagamento de doação ao meu PayPal, então eu irei resolver este problema que você mencionou: "mas depois que o registro foi salvo, o usuário não pode alterar esse campo. Então o usuário deve excluir o registro inteiro e registre tudo novamente "

Cool, how much would you think fair?

**Comment by habibieamrullah** [comment]
It's up to you broo.....
